# Basic Information 
title: Francesco Capuano
position: PhD Student
affiliation: University of Oxford (A2I & FLAIR)
email: capuano@robots.ox.ac.uk

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Francesco Capuano, Robotics, Reinforcement Learning, MVA, Paris, AI, Hugging Face, Robot Learning, Oxford
description: Personal web page of Francesco Capuano, waiter turned researcher
canonical: https://fracapuano.github.io

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?hl=fi&user=E6WpTrUAAAAJ
github_link: https://github.com/fracapuano
linkedin: https://www.linkedin.com/in/fracapuano
twitter: https://x.com/_fracapuano

# Images (e.g., your profile picture and your website's favicon) 
avatar: ./assets/img/me.jpeg
favicon:

# Footnote
enable_footnote: false

# Font
font: "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
google_analytics: G-S797TZYSYF

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/

# Markdown settings
kramdown:
  math_engine: mathjax
